slicer:
  raw_data: data/raw/volume_lines.tif
  input_dir: data/input

processor:
  input_dir: data/input
  intermediate_dir: data/intermediate

counter:
  intermediate_dir: data/intermediate
  output_csv: data/output/results.csv
